# Generated by Django 4.2.2 on 2023-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('members', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('joined', models.BooleanField()),
                ('image', models.URLField()),
            ],
        ),
    ]
