# Generated by Django 4.2.2 on 2023-06-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carhub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Groupies',
        ),
    ]
