# Generated by Django 4.2.2 on 2023-06-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carhub', '0002_rename_groups_groupies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groupies',
            new_name='Group',
        ),
    ]
