# Generated by Django 4.2.2 on 2023-06-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhub', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(max_length=5),
        ),
    ]
