# Generated by Django 4.2.2 on 2023-06-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhub', '0006_alter_profile_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
    ]
